PYTHON-3004 Support kmip FLE KMS provider (#786)
Resync CSFLE spec tests.

diff --git a/.evergreen/config.yml b/.evergreen/config.yml
--- a/.evergreen/config.yml
+++ b/.evergreen/config.yml
@@ -359,6 +359,49 @@ functions:
            PYTHON_BINARY=${PYTHON_BINARY} bash ${PROJECT_DIRECTORY}/.evergreen/run-doctests.sh
 
   "run tests":
+    # If testing FLE, start the KMS mock servers, first create the virtualenv.
+    - command: shell.exec
+      params:
+        script: |
+          if [ -n "${test_encryption}" ]; then
+            ${PREPARE_SHELL}
+            cd ${DRIVERS_TOOLS}/.evergreen/csfle
+            . ./activate_venv.sh
+          fi
+    # Run in the background so the mock servers don't block the EVG task.
+    - command: shell.exec
+      params:
+        background: true
+        script: |
+          if [ -n "${test_encryption}" ]; then
+            ${PREPARE_SHELL}
+            cd ${DRIVERS_TOOLS}/.evergreen/csfle
+            . ./activate_venv.sh
+            # The -u options forces the stdout and stderr streams to be unbuffered.
+            # TMPDIR is required to avoid "AF_UNIX path too long" errors.
+            TMPDIR="$(dirname $DRIVERS_TOOLS)" python -u kms_kmip_server.py --ca_file ../x509gen/ca.pem --cert_file ../x509gen/server.pem  --port 5698 &
+            python -u kms_http_server.py --ca_file ../x509gen/ca.pem --cert_file ../x509gen/expired.pem --port 8000 &
+            python -u kms_http_server.py --ca_file ../x509gen/ca.pem --cert_file ../x509gen/wrong-host.pem --port 8001 &
+            python -u kms_http_server.py --ca_file ../x509gen/ca.pem --cert_file ../x509gen/server.pem --port 8002 --require_client_cert &
+          fi
+    # Wait up to 10 seconds for the KMIP server to start.
+    - command: shell.exec
+      params:
+        script: |
+          if [ -n "${test_encryption}" ]; then
+            ${PREPARE_SHELL}
+            cd ${DRIVERS_TOOLS}/.evergreen/csfle
+            . ./activate_venv.sh
+            for i in $(seq 1 1 10); do
+               sleep 1
+               if python -u kms_kmip_client.py; then
+                  echo 'KMS KMIP server started!'
+                  exit 0
+               fi
+            done
+            echo 'Failed to start KMIP server!'
+            exit 1
+          fi
     - command: shell.exec
       type: test
       params:
