PYTHON-3004 Wait up to 10 seconds for the KMIP server to start

diff --git a/.evergreen/config.yml b/.evergreen/config.yml
--- a/.evergreen/config.yml
+++ b/.evergreen/config.yml
@@ -384,6 +384,24 @@ functions:
             python -u kms_http_server.py --ca_file ../x509gen/ca.pem --cert_file ../x509gen/wrong-host.pem --port 8001 &
             python -u kms_http_server.py --ca_file ../x509gen/ca.pem --cert_file ../x509gen/server.pem --port 8002 --require_client_cert &
           fi
+    # Wait up to 10 seconds for the KMIP server to start.
+    - command: shell.exec
+      params:
+        script: |
+          if [ -n "${test_encryption}" ]; then
+            ${PREPARE_SHELL}
+            cd ${DRIVERS_TOOLS}/.evergreen/csfle
+            . ./activate_venv.sh
+            for i in $(seq 1 1 10); do
+               sleep 1
+               if python -u kms_kmip_client.py; then
+                  echo 'KMS KMIP server started!'
+                  exit 0
+               fi
+            done
+            echo 'Failed to start KMIP server!'
+            exit 1
+          fi
     - command: shell.exec
       type: test
       params:
