remove all expansions created from the expansions.yml update

diff --git a/.evergreen/config.yml b/.evergreen/config.yml
--- a/.evergreen/config.yml
+++ b/.evergreen/config.yml
@@ -55,9 +55,9 @@ functions:
           . src/.evergreen/scripts/env.sh
           set -o xtrace
           rm -rf $DRIVERS_TOOLS
-          if [ "${project}" = "drivers-tools" ]; then
+          if [ "$PROJECT" = "drivers-tools" ]; then
             # If this was a patch build, doing a fresh clone would not actually test the patch
-            cp -R ${PROJECT_DIRECTORY}/ $DRIVERS_TOOLS
+            cp -R $PROJECT_DIRECTORY/ $DRIVERS_TOOLS
           else
             git clone https://github.com/mongodb-labs/drivers-evergreen-tools.git $DRIVERS_TOOLS
           fi
@@ -183,7 +183,7 @@ functions:
     - command: archive.targz_pack
       params:
         target: "working-dir.tar.gz"
-        source_dir: ${PROJECT_DIRECTORY}/
+        source_dir: $PROJECT_DIRECTORY/
         include:
           - "./**"
     - command: s3.put
@@ -200,7 +200,7 @@ functions:
     - command: archive.targz_pack
       params:
         target: "drivers-dir.tar.gz"
-        source_dir: ${DRIVERS_TOOLS}
+        source_dir: $DRIVERS_TOOLS
         include:
           - "./**"
         exclude_files:
@@ -221,7 +221,7 @@ functions:
   "upload test results":
     - command: attach.results
       params:
-        file_location: "${DRIVERS_TOOLS}/results.json"
+        file_location: "$DRIVERS_TOOLS/results.json"
     - command: attach.xunit_results
       params:
         file: "src/xunit-results/TEST-*.xml"
@@ -273,7 +273,7 @@ functions:
             ORCHESTRATION_FILE=${ORCHESTRATION_FILE} \
             REQUIRE_API_VERSION=${REQUIRE_API_VERSION} \
             LOAD_BALANCER=${LOAD_BALANCER} \
-            bash ${DRIVERS_TOOLS}/.evergreen/run-orchestration.sh
+            bash $DRIVERS_TOOLS/.evergreen/run-orchestration.sh
     # run-orchestration generates expansion file with the MONGODB_URI for the cluster
     - command: expansions.update
       params:
@@ -290,13 +290,13 @@ functions:
       params:
         script: |
           . src/.evergreen/scripts/env.sh
-          bash ${DRIVERS_TOOLS}/.evergreen/atlas_data_lake/pull-mongohouse-image.sh
+          bash $DRIVERS_TOOLS/.evergreen/atlas_data_lake/pull-mongohouse-image.sh
     - command: shell.exec
       type: setup
       params:
         script: |
           . src/.evergreen/scripts/env.sh
-          bash ${DRIVERS_TOOLS}/.evergreen/atlas_data_lake/run-mongohouse-image.sh
+          bash $DRIVERS_TOOLS/.evergreen/atlas_data_lake/run-mongohouse-image.sh
           sleep 1
           docker ps
 
@@ -306,7 +306,7 @@ functions:
         script: |
           . src/.evergreen/scripts/env.sh
           set -o xtrace
-          bash ${DRIVERS_TOOLS}/.evergreen/stop-orchestration.sh
+          bash $DRIVERS_TOOLS/.evergreen/stop-orchestration.sh
 
   "run mod_wsgi tests":
     - command: shell.exec
@@ -317,8 +317,8 @@ functions:
           . .evergreen/scripts/env.sh
           set -o xtrace
           PYTHON_BINARY=${PYTHON_BINARY} MOD_WSGI_VERSION=${MOD_WSGI_VERSION} \
-            MOD_WSGI_EMBEDDED=${MOD_WSGI_EMBEDDED} PROJECT_DIRECTORY=${PROJECT_DIRECTORY} \
-            bash ${PROJECT_DIRECTORY}/.evergreen/run-mod-wsgi-tests.sh
+            MOD_WSGI_EMBEDDED=${MOD_WSGI_EMBEDDED} PROJECT_DIRECTORY=$PROJECT_DIRECTORY \
+            bash $PROJECT_DIRECTORY/.evergreen/run-mod-wsgi-tests.sh
 
   "run mockupdb tests":
     - command: shell.exec
@@ -329,7 +329,7 @@ functions:
           . .evergreen/scripts/env.sh
           set -o xtrace
           export PYTHON_BINARY=${PYTHON_BINARY}
-          bash ${PROJECT_DIRECTORY}/.evergreen/hatch.sh test:test-mockupdb
+          bash $PROJECT_DIRECTORY/.evergreen/hatch.sh test:test-mockupdb
 
   "run doctests":
      - command: shell.exec
@@ -339,7 +339,7 @@ functions:
          script: |
            . .evergreen/scripts/env.sh
            set -o xtrace
-           PYTHON_BINARY=${PYTHON_BINARY} bash ${PROJECT_DIRECTORY}/.evergreen/hatch.sh doctest:test
+           PYTHON_BINARY=${PYTHON_BINARY} bash $PROJECT_DIRECTORY/.evergreen/hatch.sh doctest:test
 
   "run tests":
     - command: shell.exec
@@ -372,7 +372,7 @@ functions:
           if [ -n "${test_encryption}" ]; then
             # Disable xtrace (just in case it was accidentally set).
             set +x
-            bash ${DRIVERS_TOOLS}/.evergreen/csfle/await-servers.sh
+            bash $DRIVERS_TOOLS/.evergreen/csfle/await-servers.sh
             export TEST_ENCRYPTION=1
             if [ -n "${test_encryption_pyopenssl}" ]; then
               export TEST_ENCRYPTION_PYOPENSSL=1
@@ -409,7 +409,7 @@ functions:
             SSL=${SSL} \
             TEST_DATA_LAKE=${TEST_DATA_LAKE} \
             MONGODB_API_VERSION=${MONGODB_API_VERSION} \
-            bash ${PROJECT_DIRECTORY}/.evergreen/hatch.sh test:test-eg
+            bash $PROJECT_DIRECTORY/.evergreen/hatch.sh test:test-eg
 
   "run enterprise auth tests":
     - command: shell.exec
@@ -420,12 +420,12 @@ functions:
         script: |
           # Disable xtrace for security reasons (just in case it was accidentally set).
           set +x
-          bash ${DRIVERS_TOOLS}/.evergreen/auth_aws/setup_secrets.sh drivers/enterprise_auth
-          PROJECT_DIRECTORY="${PROJECT_DIRECTORY}" \
+          bash $DRIVERS_TOOLS/.evergreen/auth_aws/setup_secrets.sh drivers/enterprise_auth
+          PROJECT_DIRECTORY="$PROJECT_DIRECTORY" \
             PYTHON_BINARY="${PYTHON_BINARY}" \
             TEST_ENTERPRISE_AUTH=1 \
             AUTH=auth \
-            bash ${PROJECT_DIRECTORY}/.evergreen/hatch.sh test:test-eg
+            bash $PROJECT_DIRECTORY/.evergreen/hatch.sh test:test-eg
 
   "run atlas tests":
     - command: shell.exec
@@ -437,11 +437,11 @@ functions:
           # Disable xtrace for security reasons (just in case it was accidentally set).
           set +x
           set -o errexit
-          bash ${DRIVERS_TOOLS}/.evergreen/auth_aws/setup_secrets.sh drivers/atlas_connect
-          PROJECT_DIRECTORY="${PROJECT_DIRECTORY}" \
+          bash $DRIVERS_TOOLS/.evergreen/auth_aws/setup_secrets.sh drivers/atlas_connect
+          PROJECT_DIRECTORY="$PROJECT_DIRECTORY" \
             PYTHON_BINARY="${PYTHON_BINARY}" \
             TEST_ATLAS=1 \
-            bash ${PROJECT_DIRECTORY}/.evergreen/hatch.sh test:test-eg
+            bash $PROJECT_DIRECTORY/.evergreen/hatch.sh test:test-eg
 
   "get aws auth secrets":
     - command: subprocess.exec
@@ -450,7 +450,7 @@ functions:
         include_expansions_in_env: ["AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN"]
         binary: bash
         args:
-          - ${DRIVERS_TOOLS}/.evergreen/auth_aws/setup-secrets.sh
+          - $DRIVERS_TOOLS/.evergreen/auth_aws/setup-secrets.sh
 
   "run aws auth test with regular aws credentials":
     - command: shell.exec
@@ -546,11 +546,11 @@ functions:
           fi
           . .evergreen/scripts/env.sh
           set -ex
-          cd ${DRIVERS_TOOLS}/.evergreen/auth_aws
+          cd $DRIVERS_TOOLS/.evergreen/auth_aws
           . ./activate-authawsvenv.sh
           . aws_setup.sh ecs
-          export MONGODB_BINARIES="${MONGODB_BINARIES}";
-          export PROJECT_DIRECTORY="${PROJECT_DIRECTORY}";
+          export MONGODB_BINARIES="$MONGODB_BINARIES";
+          export PROJECT_DIRECTORY="$PROJECT_DIRECTORY";
           python aws_tester.py ecs
           cd -
 
@@ -570,8 +570,8 @@ functions:
         script: |
           set +x
           . src/.evergreen/scripts/env.sh
-          for filename in $(find ${DRIVERS_TOOLS} -name \*.json); do
-            perl -p -i -e "s|ABSOLUTE_PATH_REPLACEMENT_TOKEN|${DRIVERS_TOOLS}|g" $filename
+          for filename in $(find $DRIVERS_TOOLS -name \*.json); do
+            perl -p -i -e "s|ABSOLUTE_PATH_REPLACEMENT_TOKEN|$DRIVERS_TOOLS|g" $filename
           done
 
   "windows fix":
@@ -580,12 +580,12 @@ functions:
         script: |
           set +x
           . src/.evergreen/scripts/env.sh
-          for i in $(find ${DRIVERS_TOOLS}/.evergreen ${PROJECT_DIRECTORY}/.evergreen -name \*.sh); do
+          for i in $(find $DRIVERS_TOOLS/.evergreen $PROJECT_DIRECTORY/.evergreen -name \*.sh); do
             cat $i | tr -d '\r' > $i.new
             mv $i.new $i
           done
           # Copy client certificate because symlinks do not work on Windows.
-          cp ${DRIVERS_TOOLS}/.evergreen/x509gen/client.pem ${MONGO_ORCHESTRATION_HOME}/lib/client.pem
+          cp $DRIVERS_TOOLS/.evergreen/x509gen/client.pem $MONGO_ORCHESTRATION_HOME/lib/client.pem
 
   "make files executable":
     - command: shell.exec
@@ -593,7 +593,7 @@ functions:
         script: |
           set +x
           . src/.evergreen/scripts/env.sh
-          for i in $(find ${DRIVERS_TOOLS}/.evergreen ${PROJECT_DIRECTORY}/.evergreen -name \*.sh); do
+          for i in $(find $DRIVERS_TOOLS/.evergreen $PROJECT_DIRECTORY/.evergreen -name \*.sh); do
             chmod +x $i
           done
 
@@ -603,7 +603,7 @@ functions:
         script: |
           set +x
           . src/.evergreen/scripts/env.sh
-          echo '{"results": [{ "status": "FAIL", "test_file": "Build", "log_raw": "No test-results.json found was created"  } ]}' > ${PROJECT_DIRECTORY}/test-results.json
+          echo '{"results": [{ "status": "FAIL", "test_file": "Build", "log_raw": "No test-results.json found was created"  } ]}' > $PROJECT_DIRECTORY/test-results.json
 
   "install dependencies":
     - command: shell.exec
@@ -612,7 +612,7 @@ functions:
         script: |
           . .evergreen/scripts/env.sh
           set -o xtrace
-          file="${PROJECT_DIRECTORY}/.evergreen/install-dependencies.sh"
+          file="$PROJECT_DIRECTORY/.evergreen/install-dependencies.sh"
           # Don't use ${file} syntax here because evergreen treats it as an empty expansion.
           [ -f "$file" ] && bash $file || echo "$file not available, skipping"
 
@@ -630,7 +630,7 @@ functions:
           MONGODB_VERSION: "7.0"
           LAMBDA_STACK_NAME: dbx-python-lambda
         args:
-          - ${DRIVERS_TOOLS}/.evergreen/atlas/setup-atlas-cluster.sh
+          - $DRIVERS_TOOLS/.evergreen/atlas/setup-atlas-cluster.sh
     - command: expansions.update
       params:
         file: atlas-expansion.yml
@@ -646,7 +646,7 @@ functions:
           PYTHON_BINARY=${PYTHON_BINARY} \
           CA_FILE="$DRIVERS_TOOLS/.evergreen/ocsp/${OCSP_ALGORITHM}/ca.pem" \
           OCSP_TLS_SHOULD_SUCCEED="${OCSP_TLS_SHOULD_SUCCEED}" \
-          bash ${PROJECT_DIRECTORY}/.evergreen/hatch.sh test:test-eg
+          bash $PROJECT_DIRECTORY/.evergreen/hatch.sh test:test-eg
 
   run-valid-ocsp-server:
     - command: shell.exec
@@ -654,7 +654,7 @@ functions:
         background: true
         script: |
           . src/.evergreen/scripts/env.sh
-          cd ${DRIVERS_TOOLS}/.evergreen/ocsp
+          cd $DRIVERS_TOOLS/.evergreen/ocsp
           . ./activate-ocspvenv.sh
           python ocsp_mock.py \
           --ca_file ${OCSP_ALGORITHM}/ca.pem \
@@ -667,7 +667,7 @@ functions:
         background: true
         script: |
           . src/.evergreen/scripts/env.sh
-          cd ${DRIVERS_TOOLS}/.evergreen/ocsp
+          cd $DRIVERS_TOOLS/.evergreen/ocsp
           . ./activate-ocspvenv.sh
           python ocsp_mock.py \
           --ca_file ${OCSP_ALGORITHM}/ca.pem \
@@ -682,7 +682,7 @@ functions:
         background: true
         script: |
           . src/.evergreen/scripts/env.sh
-          cd ${DRIVERS_TOOLS}/.evergreen/ocsp
+          cd $DRIVERS_TOOLS/.evergreen/ocsp
           . ./activate-ocspvenv.sh
           python ocsp_mock.py \
           --ca_file ${OCSP_ALGORITHM}/ca.pem \
@@ -695,7 +695,7 @@ functions:
         background: true
         script: |
           . src/.evergreen/scripts/env.sh
-          cd ${DRIVERS_TOOLS}/.evergreen/ocsp
+          cd $DRIVERS_TOOLS/.evergreen/ocsp
           . ./activate-ocspvenv.sh
           python ocsp_mock.py \
           --ca_file ${OCSP_ALGORITHM}/ca.pem \
@@ -709,7 +709,7 @@ functions:
     - command: shell.exec
       params:
         script: |
-          DRIVERS_TOOLS=${DRIVERS_TOOLS} MONGODB_URI=${MONGODB_URI} bash ${DRIVERS_TOOLS}/.evergreen/run-load-balancer.sh start
+          DRIVERS_TOOLS=$DRIVERS_TOOLS MONGODB_URI=${MONGODB_URI} bash $DRIVERS_TOOLS/.evergreen/run-load-balancer.sh start
     - command: expansions.update
       params:
         file: lb-expansion.yml
@@ -718,8 +718,8 @@ functions:
     - command: shell.exec
       params:
         script: |
-          cd ${DRIVERS_TOOLS}/.evergreen
-          DRIVERS_TOOLS=${DRIVERS_TOOLS} bash ${DRIVERS_TOOLS}/.evergreen/run-load-balancer.sh stop
+          cd $DRIVERS_TOOLS/.evergreen
+          DRIVERS_TOOLS=$DRIVERS_TOOLS bash $DRIVERS_TOOLS/.evergreen/run-load-balancer.sh stop
 
   "teardown_docker":
     - command: shell.exec
@@ -737,7 +737,7 @@ functions:
         shell: "bash"
         script: |
           . src/.evergreen/scripts/env.sh
-          cd "${DRIVERS_TOOLS}/.evergreen/auth_aws"
+          cd "$DRIVERS_TOOLS/.evergreen/auth_aws"
           if [ -f "./aws_e2e_setup.json" ]; then
             . ./activate-authawsvenv.sh
             python ./lib/aws_assign_instance_profile.py
@@ -748,7 +748,7 @@ functions:
       params:
         binary: bash
         args:
-          - ${DRIVERS_TOOLS}/.evergreen/atlas/teardown-atlas-cluster.sh
+          - $DRIVERS_TOOLS/.evergreen/atlas/teardown-atlas-cluster.sh
 
   "build release":
     - command: shell.exec
@@ -843,7 +843,7 @@ functions:
         working_dir: "src"
         script: |
           . .evergreen/scripts/env.sh
-          PROJECT_DIRECTORY=${PROJECT_DIRECTORY} bash ${PROJECT_DIRECTORY}/.evergreen/run-perf-tests.sh
+          PROJECT_DIRECTORY=$PROJECT_DIRECTORY bash $PROJECT_DIRECTORY/.evergreen/run-perf-tests.sh
 
   "attach benchmark test results":
     - command: attach.results
@@ -889,13 +889,13 @@ task_groups:
           env:
             VAULT_NAME: ${VAULT_NAME}
           args:
-            - ${DRIVERS_TOOLS}/.evergreen/serverless/create-instance.sh
+            - $DRIVERS_TOOLS/.evergreen/serverless/create-instance.sh
     teardown_task:
       - command: subprocess.exec
         params:
           binary: bash
           args:
-            - ${DRIVERS_TOOLS}/.evergreen/serverless/delete-instance.sh
+            - $DRIVERS_TOOLS/.evergreen/serverless/delete-instance.sh
       - func: "upload test results"
     tasks:
       - ".serverless"
@@ -912,13 +912,13 @@ task_groups:
         params:
           binary: "bash"
           args:
-            - ${DRIVERS_TOOLS}/.evergreen/csfle/gcpkms/create-and-setup-instance.sh
+            - $DRIVERS_TOOLS/.evergreen/csfle/gcpkms/create-and-setup-instance.sh
     teardown_task:
       - command: subprocess.exec
         params:
           binary: "bash"
           args:
-            - ${DRIVERS_TOOLS}/.evergreen/csfle/gcpkms/delete-instance.sh
+            - $DRIVERS_TOOLS/.evergreen/csfle/gcpkms/delete-instance.sh
       - func: "upload test results"
     tasks:
       - testgcpkms-task
@@ -935,13 +935,13 @@ task_groups:
           env:
             AZUREKMS_VMNAME_PREFIX: "PYTHON_DRIVER"
           args:
-            - ${DRIVERS_TOOLS}/.evergreen/csfle/azurekms/create-and-setup-vm.sh
+            - $DRIVERS_TOOLS/.evergreen/csfle/azurekms/create-and-setup-vm.sh
     teardown_group:
       - command: subprocess.exec
         params:
           binary: bash
           args:
-            - ${DRIVERS_TOOLS}/.evergreen/csfle/azurekms/delete-vm.sh
+            - $DRIVERS_TOOLS/.evergreen/csfle/azurekms/delete-vm.sh
       - func: "upload test results"
     setup_group_can_fail_task: true
     teardown_task_can_fail_task: true
@@ -961,13 +961,13 @@ task_groups:
           env:
             AZUREOIDC_VMNAME_PREFIX: "PYTHON_DRIVER"
           args:
-            - ${DRIVERS_TOOLS}/.evergreen/auth_oidc/azure/create-and-setup-vm.sh
+            - $DRIVERS_TOOLS/.evergreen/auth_oidc/azure/create-and-setup-vm.sh
     teardown_task:
       - command: subprocess.exec
         params:
           binary: bash
           args:
-            - ${DRIVERS_TOOLS}/.evergreen/auth_oidc/azure/delete-vm.sh
+            - $DRIVERS_TOOLS/.evergreen/auth_oidc/azure/delete-vm.sh
     setup_group_can_fail_task: true
     setup_group_timeout_secs: 1800
     tasks:
@@ -985,13 +985,13 @@ task_groups:
           env:
             GCPOIDC_VMNAME_PREFIX: "PYTHON_DRIVER"
           args:
-            - ${DRIVERS_TOOLS}/.evergreen/auth_oidc/gcp/setup.sh
+            - $DRIVERS_TOOLS/.evergreen/auth_oidc/gcp/setup.sh
     teardown_task:
       - command: subprocess.exec
         params:
           binary: bash
           args:
-            - ${DRIVERS_TOOLS}/.evergreen/auth_oidc/gcp/teardown.sh
+            - $DRIVERS_TOOLS/.evergreen/auth_oidc/gcp/teardown.sh
     setup_group_can_fail_task: true
     setup_group_timeout_secs: 1800
     tasks:
@@ -1012,13 +1012,13 @@ task_groups:
             # PYTHON-4447
             MONGODB_VERSION: "8.0"
           args:
-            - ${DRIVERS_TOOLS}/.evergreen/auth_oidc/setup.sh
+            - $DRIVERS_TOOLS/.evergreen/auth_oidc/setup.sh
     teardown_task:
       - command: subprocess.exec
         params:
           binary: bash
           args:
-            - ${DRIVERS_TOOLS}/.evergreen/auth_oidc/teardown.sh
+            - $DRIVERS_TOOLS/.evergreen/auth_oidc/teardown.sh
     setup_group_can_fail_task: true
     setup_group_timeout_secs: 1800
     tasks:
@@ -1060,7 +1060,7 @@ tasks:
           params:
             script: |
                set -o xtrace
-               . ${DRIVERS_TOOLS}/.evergreen/download-mongodb.sh || true
+               . $DRIVERS_TOOLS/.evergreen/download-mongodb.sh || true
                get_distro || true
                echo $DISTRO
                echo $MARCH
@@ -1530,7 +1530,7 @@ tasks:
             args:
               - .evergreen/run-deployed-lambda-aws-tests.sh
             env:
-              TEST_LAMBDA_DIRECTORY: ${PROJECT_DIRECTORY}/test/lambda
+              TEST_LAMBDA_DIRECTORY: $PROJECT_DIRECTORY/test/lambda
 
     - name: test-ocsp-rsa-valid-cert-server-staples
       tags: ["ocsp", "ocsp-rsa", "ocsp-staple"]
@@ -2158,7 +2158,7 @@ tasks:
               export CONFIG=$PROJECT_DIRECTORY/.github/reviewers.txt
               export SCRIPT="$DRIVERS_TOOLS/.evergreen/github_app/assign-reviewer.sh"
               bash $SCRIPT -p $CONFIG -h ${github_commit} -o "mongodb" -n "mongo-python-driver"
-              echo '{"results": [{ "status": "PASS", "test_file": "Build", "log_raw": "Test completed"  } ]}' > ${PROJECT_DIRECTORY}/test-results.json
+              echo '{"results": [{ "status": "PASS", "test_file": "Build", "log_raw": "Test completed"  } ]}' > $PROJECT_DIRECTORY/test-results.json
 
     - name: "check-import-time"
       tags: ["pr"]
